#!/bin/bash

kgx -T "Vanilla OS - RC" \
    -e printf "\033[1;32mHi! Welcome to Vanilla OS.
=========================\033[0m
If you are reading this, you are probably a tester or a developer, so
thank you for your interest in Vanilla OS! Please read the following
information carefully.

This is a development version, so using it as a daily
driver is not recommended. If you get any error, please report it to the testing-issues
repository on GitHub or to the Vanilla OS Discord server, to help us
improve Vanilla OS before the official release.

\033[1;31mKnown issues/Disclaimer:\033[0m
- GNOME Extensions Manager does not work for some users.
- Manual partitioning is disabled currently, and it is not a bug, but it will be
  re-enabled soon.
- UEFI support is not yet fully tested.

\033[1;34mSuggested tests:\033[0m
- If you are here, well the first test is done! You got Vanilla OS running
  on your computer (either live or physically).
- If you are in Live mode, try to install Vanilla OS on your computer.
- Complete the First Setup Wizard on the first boot after installation.
- Try installing packages in the system with the `apx install <package>` command.
- Try installing AUR packages in a container using the `apx install --aur <package>` command.
- Try installing DNF packages in a container using the `apx install --dnf <package>` command.
- Try launching the applications you just installed with 'apx run <application>'.
- Try forcing a system update using the `vso trigger-update --now` command.
- Verify that A and B partitions are well recognized with: `abroot get present` 
and `abroot get future` commands.
"
