#!/bin/bash

kgx -T "Vanilla OS - RC" \
    -e printf "\033[1;32mHi! Welcome to Vanilla OS.
=========================\033[0m
If you are reading this, you are probably a tester or a developer, so
thank you for your interest in Vanilla OS! Please read the following
information carefully.

This is a development version, so it is not recommended to use it as a daily
driver. If you get any error, please report it to the testing-issues
repository on GitHub or to the Vanilla OS Discord server, to help us
improve Vanilla OS before the official release.

\033[1;31mKnown issues/Disclaimer:\033[0m
- GNOME Extensions Manager does not work for some users.
- Manual partitioning is disabled, not really a bug, but it will be
  re-enabled in the near future.
- UEFI support is not yet fully tested.

\033[1;34mSuggested tests:\033[0m
- If you are here, well the first test is done! You got Vanilla OS running
  on your computer (live or not).
- If in Live mode, try to install Vanilla OS on your computer.
- Complete the First Setup Wizard on the first boot (enable immutability and
  subsystem).
- Try to install any package with 'apx install <package>'.
- Try launching the application you just installed with 'apx run <application>'.
- Try forcing an update with `vso trigger-update --now`.
- Verify that A and B partitions are well recognized with: `abroot get present` 
and `abroot get future`.
